### PR TITLE
Fix Network Debugging Swizzle Guard

### LINKED ISSUE #141: HTTP response body data double-logged for NSURLSession-based response
When using an NSURLSession-based connection (e.g. AFNetworking 2.0), PonyDebugger is reporting invalid JSON response bodies. After a little investigation, I see that the JSON response body is actually double-logged, making it invalid JSON. (This prevents the Chrome tools built-in display of the JSON as an object, etc.)

I did a bit more digging and found that `[PDNetworkDomainController addAccumulatedData:forTask:]` is being called twice with the same `data` for the same `task` -- once in the "running" state and once in the "completed" state.

I suspect this has to do with the recent-ish changes for support NSURLSession connections.

### PR DESCRIPTION
**Pull request by ryanolsonk**
This fixes #141 raised by @mthole 

There was previously no working guard against sniffing the same network event multiple times. This can happen when we swizzle both a class and a superclass that implement one of the delegate methods. Previously, we would log duplicate network events if the class called through to the swizzled method on its superclass. By detecting nested calls, we now avoid the duplicated sniffing.

The issue isn't limited to passing messages up to the superclass, but happens with any forwarding from inside the delegate callback. For example, AFNetworking uses internal delegate objects in `AFURLSessionManager` (see https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFURLSessionManager.m#L109). If `forwardAllNetworkTraffic` is used, we'll swizzle the methods on both `AFURLSessionManager` and `AFURLSessionManagerTaskDelegate`. We need a guard to ensure we only sniff the network event for the first delegate call, and ignore it on any nested forwarding.

### CODE REVIEW

**Comment by mthole** [comment]
Awesome, thanks for digging into this @ryanolsonk. I'll take a look this weekend.

File: ObjC/PonyDebugger/PDNetworkDomainController.m [hunk 1]
```diff
@@ -137,14 +137,22 @@ + (SEL)swizzledSelectorForSelector:(SEL)selector;
     return NSSelectorFromString([NSString stringWithFormat:@"_pd_swizzle_%x_%@", arc4random(), NSStringFromSelector(selector)]);
 }
 
-+ (void)domainControllerSwizzleGuardForSwizzledObject:(NSObject *)object selector:(SEL)selector implementationBlock:(void (^)(void))implementationBlock;
+/// All swizzled delegate methods should make use of this guard.
+/// This will prevent duplicated sniffing when the original implementation calls up to a superclass implementation which we've also swizzled.
+/// The superclass implementation (and implementations in classes above that) will be executed without inteference if called from the original implementation.
++ (void)sniffWithoutDuplicationForObject:(NSObject *)object selector:(SEL)selector sniffingBlock:(void (^)(void))sniffingBlock originalImplementationBlock:(void (^)(void))originalImplementationBlock
```
Comment (mthole) [inline ObjC/PonyDebugger/PDNetworkDomainController.m]: The `sniff` naming here is pretty strange. Why not `swizzleWithoutDuplication....`?

Comment (ryanolsonk) [inline ObjC/PonyDebugger/PDNetworkDomainController.m]: There's no swizzling happening in this method. It's the network sniffing (or observing, recording, snooping, whatever) that we're trying to prevent duplicating. Maybe `record` or `observe` would be more clear? I'm not attached to the naming.

Comment (mthole) [inline ObjC/PonyDebugger/PDNetworkDomainController.m]: Ah, I see what you mean. Swizzle wouldn't be the right naming either. I'm not a huge fan of `sniff` still, but I'm not sure I've got a better alternative.

**Comment by mthole** [comment]
LGTM

**Comment by mthole** [comment]
FYI, released v0.4.2 to CocoaPods with this fix. Thanks again, @ryanolsonk !

File: ObjC/PonyDebugger/PDNetworkDomainController.m (hunk 1 above)
Comment (ryanolsonk) [inline ObjC/PonyDebugger/PDNetworkDomainController.m]: Yea, I don't love the name either. I'm happy to change it (or see it changed) if someone has a better idea in the future.

**Comment by ryanolsonk** [comment]
:thumbsup: Thanks @mthole
